"""empty message

Revision ID: 8e3f86772844
Revises: 9b42afb87967
Create Date: 2019-06-19 17:01:26.240751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e3f86772844'
down_revision = '9b42afb87967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('redirect_uri', sa.String(length=255), nullable=False))
    op.add_column('application', sa.Column('web_url', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'application', ['redirect_uri'])
    op.create_unique_constraint(None, 'application', ['web_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_column('application', 'web_url')
    op.drop_column('application', 'redirect_uri')
    # ### end Alembic commands ###
