"""empty message

Revision ID: 9b42afb87967
Revises: cd83989f5e6c
Create Date: 2019-06-19 16:40:07.932047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b42afb87967'
down_revision = 'cd83989f5e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('client_secret', sa.String(length=128), nullable=True))
    op.drop_column('application', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('application', 'client_secret')
    # ### end Alembic commands ###
