"""empty message

Revision ID: ad3dd310f9c5
Revises: 9cc9a23d4b23
Create Date: 2019-06-18 08:11:54.735518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad3dd310f9c5'
down_revision = '9cc9a23d4b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('reg_token', sa.String(length=40), nullable=True))
    op.alter_column('application', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('application', 'reg_token')
    # ### end Alembic commands ###
