"""empty message

Revision ID: bcfb4d34d8d2
Revises: 452c471a22e4
Create Date: 2019-06-15 14:17:35.163723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfb4d34d8d2'
down_revision = '452c471a22e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
