"""empty message

Revision ID: bef63b5d613d
Revises: 5cd292ff44d6
Create Date: 2019-06-18 10:12:40.522175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bef63b5d613d'
down_revision = '5cd292ff44d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('application', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('application', sa.Column('is_allowed', sa.Boolean(), nullable=True))
    op.alter_column('application', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('application', 'name')
    op.drop_column('application', 'is_allowed')
    op.drop_column('application', 'description')
    # ### end Alembic commands ###
