"""empty message

Revision ID: cd83989f5e6c
Revises: bef63b5d613d
Create Date: 2019-06-18 10:20:51.006516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd83989f5e6c'
down_revision = 'bef63b5d613d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'application', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_column('application', 'email')
    # ### end Alembic commands ###
